ci:
    autofix_prs: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files # prevents adding large files
    - id: detect-private-key # detects private keys
    - id: fix-byte-order-marker # fixes BOM
    - id: fix-encoding-pragma # fixes encoding pragma
    - id: no-commit-to-branch # prevents committing to protected branches
    - id: trailing-whitespace # prevents trailing whitespace

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        language_version: python3.10

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8

-   repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.7
    hooks:
    # - id: dbt-deps
    # - id: dbt-parse
    #   args: ["--cmd-flags", "++profiles-dir", "./queries"]
    - id: check-script-semicolon
    - id: check-script-has-no-table-name
    - id: check-model-has-description
      name: Check model description - example
      files: ^queries/models/example

# -   repo: https://github.com/tconbeer/sqlfmt
#     rev: v0.23.2
#     hooks:
#     -   id: sqlfmt
#         language_version: python
#         additional_dependencies: ['.[jinjafmt]']
